# ALL VARIABLES ARE DOCUMENTED IN THE README

all:
  vars:
    app_server_address: "10.1.20.11"

  children:
    servers:
      hosts:
        10.1.1.5:
          ansible_connection: ssh
          ansible_user: "ubuntu"
          ansible_become: true
          ansible_ssh_private_key_file: "/path/to/privatekeyfile"
          add_ubuntu_interface: true
          app_server_gateway: "10.1.20.1"

    big_ips:
      hosts:
        10.1.1.4:
          bigip_provider:
            server: "{{ inventory_hostname }}"
            user: admin
            password: admin
            validate_certs: false
          bigip_domain: "ap-southeast-2.compute.internal"
          bigip_hostname: "ip-{{ inventory_hostname_short | replace('.', '-')}}.{{ bigip_domain }}"
          juiceshop_virtual_address: "10.1.10.20"
          grafana_virtual_address: "10.1.10.21"
          log_pool: "10.1.20.9"